### ISSUE TITLE
dtype not fully set in lazy loading

### ISSUE THREAD

**Issue by tomsail** [seareport/xarray-selafin#29]
I am not sure why yet, but a simple printing of the dataset throws out the following error: 
```
>>> ds = xr.open_dataset('r3d_tidal_flats.slf', engine = 'selafin')
>>> ds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomsail/miniconda3/envs/xr-slf/lib/python3.11/site-packages/xarray/core/dataset.py", line 2534, in __repr__
    return formatting.dataset_repr(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomsail/miniconda3/envs/xr-slf/lib/python3.11/reprlib.py", line 21, in wrapper
    result = user_function(self)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/tomsail/miniconda3/envs/xr-slf/lib/python3.11/site-packages/xarray/core/formatting.py", line 713, in dataset_repr
    nbytes_str = render_human_readable_nbytes(ds.nbytes)
                                              ^^^^^^^^^
  File "/home/tomsail/miniconda3/envs/xr-slf/lib/python3.11/site-packages/xarray/core/dataset.py", line 1515, in nbytes
    return sum(v.nbytes for v in self.variables.values())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomsail/miniconda3/envs/xr-slf/lib/python3.11/site-packages/xarray/core/dataset.py", line 1515, in <genexpr>
    return sum(v.nbytes for v in self.variables.values())
               ^^^^^^^^
  File "/home/tomsail/miniconda3/envs/xr-slf/lib/python3.11/site-packages/xarray/namedarray/core.py", line 476, in nbytes
    return self.size * self.dtype.itemsize
           ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'int' and 'getset_descriptor'
```
It seems to be connected with the definition of the `self.dtype` class variable. 

`print(ds.variables)` also throws the same error but: 
```
print([var for var in ds.variables])
['Z', 'U', 'V', 'W', 'MUD', 'x', 'y', 'time']
```
works. 

So far I have been able to work around this problem (also because we can set `lazy_loading = False` when reading the file). 
But the bug needs to : 
 * be identified
 * be added to tests too

**Comment by lucduron** [comment]
I can not reproduce the problem (with Python 3.11.5, numpy 1.25.2)? It is not working at all in lazy loading for any Selafin file?

Could we add `print(ds_slf)` in `test_to_selafin` and `test_to_selafin_eager_mode`?

**Comment by pmav99** [comment]
You are hardcoding the dtype to float64 which may be related: https://github.com/seareport/xarray-selafin/blob/bf2e8ac8ece9eddbcdb42e89223caf00efcc541d/xarray_selafin/xarray_backend.py#L287

This seems to fix it:
``` diff
diff --git a/tests/io_test.py b/tests/io_test.py
index 40f518b..f125938 100644
--- a/tests/io_test.py
+++ b/tests/io_test.py
@@ -29,6 +29,7 @@ def write_netcdf(ds, nc_out):
 def test_open_dataset(slf_in):
     ds = xr.open_dataset(slf_in, engine="selafin")
     assert isinstance(ds, xr.Dataset)
+    repr(ds)  # to trigger the bug
 
     # Dimensions
     assert ds.sizes["time"] == 17
diff --git a/xarray_selafin/xarray_backend.py b/xarray_selafin/xarray_backend.py
index c7e6359..9caafc8 100644
--- a/xarray_selafin/xarray_backend.py
+++ b/xarray_selafin/xarray_backend.py
@@ -284,7 +284,6 @@ class SelafinBackendEntrypoint(BackendEntrypoint):
 
         # Create data variables
         data_vars = {}
-        dtype = np.float64
 
         if nplan == 0:
             shape = (len(times), npoin2)
@@ -295,11 +294,11 @@ class SelafinBackendEntrypoint(BackendEntrypoint):
 
         for var in vars:
             if lazy_loading:
-                lazy_array = SelafinLazyArray(slf, var, dtype, shape)
+                lazy_array = SelafinLazyArray(slf, var, slf.header.np_type, shape)
                 data = indexing.LazilyIndexedArray(lazy_array)
                 data_vars[var] = xr.Variable(dims=dims, data=data)
             else:
-                data = np.empty(shape, dtype=dtype)
+                data = np.empty(shape, dtype=slf.header.np_type)
                 for time_index, t in enumerate(times):
                     values = slf.read_var_in_frame(time_index, var)
                     if is_2d:
```

But I haven't looked carefully enough to understand if this is the proper fix or not.

**Comment by tomsail** [comment]
Thanks guys.
I think the correct way to check this is to implement a simple 
```python 
def test_print(ds)
    print(ds)
```
in the CI. 

I'll try this and merge changes if everything looks good.
